<?php
/**
 * Created by PhpStorm.
 * User: debasis
 * Date: 16/6/15
 * Time: 12:04 AM
 */
header('Content-type: text/html');
header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');


function event_init() // init function called by defaulted when this module loaded by system
{

    //echo $GLOBALS['theme'];
    //echo 5656;
    //echo user_authenticate('debasis','Pp@ss1234');

//echo "kl";
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');



}

function event_menu()
{
    $items = array();

    $items['addevent'] = array(
        'title' => 'Add event',
        'page callback' => 'addevent',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['eventlist'] = array(
        'title' => 'event List',
        'page callback' => 'eventlist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
   $items['eventupdatestatus'] = array(
        'title' => 'status Change',
        'page callback' => 'eventupdatestatus',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
   $items['deleteevent'] = array(
        'title' => 'event Delete',
        'page callback' => 'deleteevent',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
   $items['eventdetails'] = array(
        'title' => 'event details',
        'page callback' => 'eventdetails',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['eventupdates'] = array(
        'title' => 'event Updates',
        'page callback' => 'eventupdates',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['uploadeventbanner'] = array(
        'title' => 'event Updates',
        'page callback' => 'uploadeventbanner',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
     return $items;
}


function eventdetails(){
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $queryu = db_select('users', 'u');
    $queryu->join('event', 'f', 'f.user_id = u.uid');
     $queryu->fields('u', array('uid','created','status','login','mail'));
    $queryu->fields('f',array('fname','lname','phone_no','mobile_no','address','contact_time','refferal_code','bname'))
        ->condition('u.uid', $_POST['uid'], '=');

    //->range(0, 20);
    $resultu = $queryu->execute();

   

    while($recordu = $resultu->fetchAssoc()) {
        $thisuser = user_load($recordu['uid']);
         $picture=$thisuser->picture;
         if(isset($picture->uri))$picture= image_style_url('thumbnail', $picture->uri);
         else $picture='';

        $userlist['uid'] = $recordu['uid'];
        $userlist['created'] = $recordu['created'];
        $userlist['status'] = $recordu['status'];
        $userlist['login'] = $recordu['login'];
        $userlist['email'] = $recordu['mail'];
        $userlist['fname'] = $recordu['fname'];
        $userlist['lname'] = $recordu['lname'];
        $userlist['phone_no'] = $recordu['phone_no'];
        $userlist['mobile_no'] = $recordu['mobile_no'];
        $userlist['address'] = $recordu['address'];
        $userlist['contact_time'] = $recordu['contact_time'];
        $userlist['refferal_code'] = $recordu['refferal_code'];
        $userlist['bname'] = $recordu['bname'];
        $userlist['picture'] = $picture;
    }
    echo json_encode(@$userlist);

}


function eventlist()
{
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $userlist = array();

    $queryu = db_select('event', 'ev');

    $queryu->fields('ev', array('event_name','event_description','event_image','event_status', 'event_daterange', 'event_timerange','event_create_time'));
        // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
       // ->condition('ur.rid', 5, '=');
    //->condition('u.uid', 74, '=');
    //->range(0, 20);
    $resultu = $queryu->execute();


    if ($resultu->rowCount() > 0) {
        $i = 0;
        while ($recordu = $resultu->fetchAssoc()) {


            $eventlist[$i]['event_name'] = $recordu['event_name'];
            $eventlist[$i]['event_description'] = $recordu['event_description'];
            $eventlist[$i]['event_image'] = $recordu['event_image'];
            $eventlist[$i]['event_status'] = $recordu['event_status'];
            $eventlist[$i]['event_daterange'] = $recordu['event_daterange'];
            $eventlist[$i]['event_timerange'] = $recordu['event_timerange'];
            $eventlist[$i]['event_create_time'] = $recordu['event_create_time'];

            $i++;

    }
}
    //  $records['user']=$userlist;



    echo json_encode(@$eventlist);



}

function addevent(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $user = user_load_by_mail(trim(@$_POST['email']));

    //print_r($_POST);
    ///exit;
    if($_POST['event_status']) $_POST['event_status']=1;
    else $_POST['event_status']=0;


        $query = db_insert('event')->fields(array('user_id','event_name','event_description','event_image','event_status', 'event_daterange', 'event_timerange','event_create_time'));
        //foreach ($values as $record) {
        $query->values(array(1,@$_POST['event_name'],@$_POST['event_description'],@$_POST['event_image'],@$_POST['event_status'],@$_POST['event_daterange'],@$_POST['timer'], time()));
        //}
        $query->execute();


    $data['status'] = 'success';
     echo json_encode($data);
    return;
}
function eventupdates(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

     $roles = array(
        DRUPAL_AUTHENTICATED_RID => 'authenticated user',
        // 5 => 'General Users',
    );
    $roles[5]='event';
    $user_fields = user_load(@intval($_POST['uid']));
    $user_fields->roles=$roles;
    user_save($user_fields);


    db_update('event')
        //->expression('weight', 'weight + :weight', array(':weight' => 1))
        ->fields(array( 'fname'=>@$_POST['fname'], 'lname'=>@$_POST['lname'], 'bname'=>$_POST['bname'],'address'=>@$_POST['address'],'phone_no'=>@$_POST['phone_no'],'mobile_no'=>@$_POST['mobile_no'],'contact_time'=>@$_POST['contact_time']))
        ->condition('user_id', intval($_POST['uid']))
         ->execute();
}

function eventupdatestatus(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    //print_r($_POST);
    $user_fields = user_load(@intval($_POST['uid']));
    //$user_fields = user_load(62);
    $user_fields->status=1-intval($user_fields->status);
    user_save($user_fields);

    if($user_fields->status==1) drupal_mail('user', 'register_status_activated', $_POST['email'], NULL, array('account' => $user_fields), variable_get('site_mail', 'support@voortal.com'));
    else drupal_mail('user', 'register_status_blocked', $_POST['email'], NULL, array('account' => $user_fields), variable_get('site_mail', 'support@voortal.com'));
    //drupal_mail('user', 'register_status_blocked', $_POST['email'], NULL, array('account' => $user_fields), variable_get('site_mail', 'support@voortal.com'));
    //drupal_mail('user', 'register_no_approval_required', $_POST['email'], NULL, array('account' => $user_fields), variable_get('site_mail', 'support@voortal.com'));
    echo "true";
}

function deleteevent(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    //$user = user_load_by_mail(trim(@$_POST['email']));

    //print_r($_POST);
    user_delete(@intval($_POST['uid']));
    $num_deleted = db_delete('event')
        ->condition('user_id', @$_POST['uid'])
        ->execute();

}

 function uploadeventbanner(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
     set_time_limit(0);

     $target_dir = realpath(dirname(__FILE__))."/uploads/";
     $path_parts = pathinfo($_FILES['Filedata']['name']);
     $filename = rand().'_'.time().'.'.$path_parts['extension'];

     $profile_url = '';

     if (move_uploaded_file($_FILES["Filedata"]["tmp_name"], $target_dir.$filename)) {
         //$account = user_load($_POST['userid']);

         $filepath = ($target_dir.$filename);

         $file = (object) array(
             'uid' => 1,
             'uri' => $filepath,
             'filemime' => file_get_mimetype($filepath),
             'status' => 1,
         );
         if ($file) {
// Move the file, into the Drupal file system
             if ($file = file_move($file, 'public://')) {
                 $file->status = FILE_STATUS_PERMANENT;
                 // $file->file_display = 1;
                 $file = file_save($file);
                 //set the extra values needed to make node_save work
                 $file->display = 1;
                 $file->description = "";
             }

             /* db_update('ideas')
                  //->expression('weight', 'weight + :weight', array(':weight' => 1))
                  ->fields(array( 'logo'=>@$file->uri))
                  ->condition('id', intval($_POST['id']))
                  //->condition('type', 'module')
                  ->execute();*/
         }

         /*$file = file_copy($file, 'public://');
         $edit['picture'] = $file;
         user_save($account, $edit);

         $filepath = $file->uri;
         $profile_url = image_style_url('thumbnail', $filepath);*/
     }

     $data['image_url']= image_style_url('thumbnail',(@$file->uri));
     $data['image_name']= (@$file->uri);
     echo json_encode(@$data) ;

}


