<?php
/**
 * Created by PhpStorm.
 * User: debasis
 * Date: 16/6/15
 * Time: 12:04 AM
 */
$crossoriginallowed="http://voortal.hagencompaniesonline.com";

header('Content-type: text/html');
header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');


function idea_init() // init function called by defaulted when this module loaded by system
{

    //echo $GLOBALS['theme'];
    //echo 5656;
    //echo user_authenticate('debasis','Pp@ss1234');

//echo "kl";
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headersiˆ: Content-Type, Content-Range, Content-Disposition, Content-Description');



}

function idea_menu()
{
    $items = array();

    $items['addidea'] = array(
        'title' => 'login',
        'page callback' => 'addidea',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );

 $items['ideasstepupdate'] = array(
        'title' => 'login',
        'page callback' => 'ideasstepupdate',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
$items['idealist'] = array(
        'title' => 'login',
        'page callback' => 'idealist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['fullidealist'] = array(
        'title' => 'login',
        'page callback' => 'fullidealist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['myidealist'] = array(
        'title' => 'login',
        'page callback' => 'myidealist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
$items['ideadetail'] = array(
        'title' => 'login',
        'page callback' => 'ideadetail',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
$items['addidealogo'] = array(
        'title' => 'login',
        'page callback' => 'addidealogo',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
$items['addidealogonew'] = array(
        'title' => 'login',
        'page callback' => 'addidealogonew',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );


    return $items;
}



function industryup2date(){


    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');




    db_update('industry')
        //->expression('weight', 'weight + :weight', array(':weight' => 1))
        ->fields(array( 'name'=>@$_POST['name'], 'status'=>@$_POST['status']))
        ->condition('id', intval($_POST['id']))
        //->condition('type', 'module')
        ->execute();

}

function ideasstepupdate(){


    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');


    //print_r($_POST);

    if(is_array(@$_POST['index'])){
        foreach($_POST['index'] as $index=>$value){

            echo "field=".$value."and value =".$_POST['values'][$index];
            db_update('ideas')
                //->expression('weight', 'weight + :weight', array(':weight' => 1))
                ->fields(array( $value=>@$_POST['values'][$index],'timecreated'=>time()))
                ->condition('id', intval($_POST['id']))
                //->condition('type', 'module')
                ->execute();

        }



    }



}



function addidea(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');



        //$_POST['fname']='iu';

        $data['id'] = db_insert('ideas')->fields(array( 'name', 'concept_summery','user_id','timecreated','remarks','websites','potential_brands','companies','customer_description','why','logo'))
            ->values(array(@$_POST['name'],@$_POST['concept_summery'],@$_POST['user_id'],time(),'','',@$_POST['potential_brands'],'','','',@$_POST['logo']))->execute();

    /*$id = db_insert('ideas')
        ->fields(array(
            'intvar' => 5,
            'stringvar' => 'hello world',
            'floatvar' => 3.14,
        ))
        ->execute();*/


    //print_r($_POST);
    //echo "roles :<br>";
    //print_r($roles);
    $data['status'] = 'success';
    //$data['id'] = db_last_insert_id('ideas', 'id');

    //$data['msg'] = 'Email already exists..';
    echo json_encode($data);
    return;

}

function addidealogo(){
    //header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Credentials: true');

    header('Access-Control-Allow-Headers: Content-Type, Depth,
    User-Agent, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control');


    $target_dir = realpath(dirname(__FILE__))."/uploads/idealogo/";
    $path_parts = pathinfo($_FILES['Filedata']['name']);
    $filename = rand().'_'.time().'.'.$path_parts['extension'];

    $profile_url = '';

    if (move_uploaded_file($_FILES["Filedata"]["tmp_name"], $target_dir.$filename)) {
        //$account = user_load($_POST['userid']);

        $filepath = ($target_dir.$filename);

        $file = (object) array(
            'uid' => 1,
            'uri' => $filepath,
            'filemime' => file_get_mimetype($filepath),
            'status' => 1,
        );
        if ($file) {
// Move the file, into the Drupal file system
            if ($file = file_move($file, 'public://')) {
                $file->status = FILE_STATUS_PERMANENT;
                // $file->file_display = 1;
                $file = file_save($file);
                //set the extra values needed to make node_save work
                $file->display = 1;
                $file->description = "";
            }

            db_update('ideas')
                //->expression('weight', 'weight + :weight', array(':weight' => 1))
                ->fields(array( 'logo'=>@$file->uri))
                ->condition('id', intval($_POST['id']))
                //->condition('type', 'module')
                ->execute();
        }

        /*$file = file_copy($file, 'public://');
        $edit['picture'] = $file;
        user_save($account, $edit);

        $filepath = $file->uri;
        $profile_url = image_style_url('thumbnail', $filepath);*/
    }

    echo image_style_url('thumbnail',(@$file->uri));
}


function addidealogonew(){
    //header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Credentials: true');

    header('Access-Control-Allow-Headers: Content-Type, Depth,
    User-Agent, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control');


    $target_dir = realpath(dirname(__FILE__))."/uploads/idealogo/";
    $path_parts = pathinfo($_FILES['Filedata']['name']);
    $filename = rand().'_'.time().'.'.$path_parts['extension'];

    $profile_url = '';

    if (move_uploaded_file($_FILES["Filedata"]["tmp_name"], $target_dir.$filename)) {
        //$account = user_load($_POST['userid']);

        $filepath = ($target_dir.$filename);

        $file = (object) array(
            'uid' => 1,
            'uri' => $filepath,
            'filemime' => file_get_mimetype($filepath),
            'status' => 1,
        );
        if ($file) {
// Move the file, into the Drupal file system
            if ($file = file_move($file, 'public://')) {
                $file->status = FILE_STATUS_PERMANENT;
                // $file->file_display = 1;
                $file = file_save($file);
                //set the extra values needed to make node_save work
                $file->display = 1;
                $file->description = "";
            }

           /* db_update('ideas')
                //->expression('weight', 'weight + :weight', array(':weight' => 1))
                ->fields(array( 'logo'=>@$file->uri))
                ->condition('id', intval($_POST['id']))
                //->condition('type', 'module')
                ->execute();*/
        }

        /*$file = file_copy($file, 'public://');
        $edit['picture'] = $file;
        user_save($account, $edit);

        $filepath = $file->uri;
        $profile_url = image_style_url('thumbnail', $filepath);*/
    }

    $data['image_url']= image_style_url('thumbnail',(@$file->uri));
    $data['image_name']= (@$file->uri);
    echo json_encode(@$data) ;
}

function idealist(){
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $records=array();

    $query = db_select('ideas', 'i');
    //$query->join('user_table', 'ut', 'u.uid = ut.userid');
    $query->fields('i', array('id','name','concept_summery','why','service_for',
        'industry','customer_description','competetion','companies',
        'websites','potential_brands','logo','status','remarks'))
    //$query->fields('ut',array('fname','lname'));
    // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
    ->condition('i.status', 1, '=')
    ->condition('i.is_blocked', 0, '=')
        ->orderBy('i.timecreated','DESC');
    //->range(0, 20);
    $result = $query->execute();

    while($record = $result->fetchAssoc()) {


        $queryin = db_select('industry', 'ind');
        //$query->join('user_table', 'ut', 'u.uid = ut.userid');
        $queryin->fields('ind', array('id','name'))
            //$query->fields('ut',array('fname','lname'));
            // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
            ->condition('ind.id', intval(@$record['industry']), '=');
        //->range(0, 20);
        $resultin = $queryin->execute();
        $recordin = $resultin->fetchAssoc();
        $record['industryname']=$recordin['name'];
        $record['logo_big']=image_style_url('home-idea',(@$record['logo']));
        $record['logo']=image_style_url('thumbnail',(@$record['logo']));

        $record['timecreated']=date('m/d/Y',@$record['timecreated']);
        //print_r($record);
        //$record['id']=time_elapsed_string($record['created']);
        //$record['id']=($record['created']);
        //// echo "<br>";
        $records[]=$record;

    }

    echo json_encode(@$records);

}

function fullidealist(){
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $records=array();

    $query = db_select('ideas', 'i');
    //$query->join('user_table', 'ut', 'u.uid = ut.userid');
    $query->fields('i', array('id','name','concept_summery','why','service_for',
        'industry','customer_description','competetion','companies',
        'websites','potential_brands','logo','status','is_blocked','remarks','timecreated'))
        //$query->fields('ut',array('fname','lname'));
        // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
        //->condition('i.status', 1, '=')
        //->condition('i.is_blocked', 0, '=')
        ->orderBy('i.timecreated','DESC');
    //->range(0, 20);
    $result = $query->execute();

    while($record = $result->fetchAssoc()) {




        $queryin = db_select('industry', 'ind');
        //$query->join('user_table', 'ut', 'u.uid = ut.userid');
        $queryin->fields('ind', array('id','name'))
            //$query->fields('ut',array('fname','lname'));
            // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
            ->condition('ind.id', intval(@$record['industry']), '=');
        //->range(0, 20);
        $resultin = $queryin->execute();
        $recordin = $resultin->fetchAssoc();
        $record['industryname']=$recordin['name'];
        $record['logo']=image_style_url('thumbnail',(@$record['logo']));
        $record['logo-big']=image_style_url('home-idea',(@$record['logo']));
        //$record['timecreated']=date('m/d/Y',@$record['timecreated']);
        //print_r($record);
        $record['logo']=image_style_url('thumbnail',(@$record['logo']));
        $record['logo-big']=image_style_url('home-idea',(@$record['logo']));
        //$record['timecreated']=date('m/d/Y',@$record['timecreated']);
        //$record['id']=time_elapsed_string($record['created']);
        //$record['id']=($record['created']);
        //// echo "<br>";
        $records[]=$record;

    }

    echo json_encode(@$records);

}



function myidealist(){
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $records=array();

    $query = db_select('ideas', 'i');
    //$query->join('user_table', 'ut', 'u.uid = ut.userid');
    $query->fields('i', array('id','name','concept_summery','why','service_for',
        'industry','customer_description','competetion','companies',
        'websites','potential_brands','logo','status','is_blocked','remarks'))
    //$query->fields('ut',array('fname','lname'));
    // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
    ->condition('i.user_id', @$_POST['userid'], '=')
    //->condition('i.is_blocked', 0, '=')
        ->orderBy('i.timecreated','DESC');
    //->range(0, 20);
    $result = $query->execute();

    while($record = $result->fetchAssoc()) {



        $queryin = db_select('industry', 'ind');
        //$query->join('user_table', 'ut', 'u.uid = ut.userid');
        $queryin->fields('ind', array('id','name'))
            //$query->fields('ut',array('fname','lname'));
            // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
            ->condition('ind.id', intval(@$record['industry']), '=');
        //->range(0, 20);
        $resultin = $queryin->execute();
        $recordin = $resultin->fetchAssoc();
        $record['industryname']=$recordin['name'];
        $record['logo']=image_style_url('thumbnail',(@$record['logo']));
        $record['logo-big']=image_style_url('home-idea',(@$record['logo']));
        $record['timecreated']=date('m/d/Y',@$record['timecreated']);
        //print_r($record);
        //$record['id']=time_elapsed_string($record['created']);
        //$record['id']=($record['created']);
        //// echo "<br>";
        $records[]=$record;

    }

    echo json_encode(@$records);

}



function industryd4elete(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    //$user = user_load_by_mail(trim(@$_POST['email']));

    //print_r($_POST);
    //user_delete(@intval($_POST['uid']));
    $num_deleted = db_delete('industry')
        ->condition('id', @$_POST['id'])
        ->execute();

}




function ideadetail(){
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $query = db_select('ideas', 'i');
    //$query->join('user_table', 'ut', 'u.uid = ut.userid');
    $query->fields('i', array('id','name','concept_summery','why','service_for',
        'industry','customer_description','competetion','companies',
        'websites','potential_brands','logo','status','user_id','timecreated','remarks','has_company_name','has_financial_projections','has_comprtitive_analysis','has_marketing_plan','has_business_plan','has_marketing_plan','has_comprtitive_analysis','has_financial_projections','has_it_security'))
    //$query->fields('ut',array('fname','lname'));
    // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
    ->condition('i.id', @$_POST['id'], '=');
    //->range(0, 20);
    $result = $query->execute();

    while($record = $result->fetchAssoc()) {
        //print_r($record);
        //$record['id']=time_elapsed_string($record['created']);
        //$record['id']=($record['created']);
        //// echo "<br>";




        $queryin = db_select('industry', 'ind');
        //$query->join('user_table', 'ut', 'u.uid = ut.userid');
        $queryin->fields('ind', array('id','name'))
            //$query->fields('ut',array('fname','lname'));
            // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
            ->condition('ind.id', intval(@$record['industry']), '=');
        //->range(0, 20);
        $resultin = $queryin->execute();
        $recordin = $resultin->fetchAssoc();
        $record['industryname']=$recordin['name'];
        if(strlen($record['logo'])>5)
            if(strlen($record['logo'])>0)$record['logo']=image_style_url('thumbnail',(@$record['logo']));
            if(strlen($record['logo'])>0)if($record['logo'])$record['logo-big']=image_style_url('home-idea',(@$record['logo']));
        else $record['logo-big']='';
            $record['timecreated']=date('m/d/Y',@$record['timecreated']);




        $queryu = db_select('users', 'u');
        $queryu->join('user_table', 'ut', 'u.uid = ut.userid');
        $queryu->fields('u', array('uid','name','mail','status','created'),'ut',array('fname','lname'));
        $queryu->fields('ut',array('fname','lname','about','location','education','skills'))
            // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
            ->condition('u.uid', $record['user_id'], '=');
        //->range(0, 20);
        $resultu = $queryu->execute();

        while($recordu = $resultu->fetchAssoc()) {
            //print_r($record);
            //$record['roles']=
            //// echo "<br>";
            $thisuser = user_load($recordu['uid']);
            // var_dump($thisuser);
            //$record['roles']=$thisuser->roles;
            foreach($thisuser->roles as $index=>$val){
                if($index!=2) $recordu['roles']=$index;
            }
            $picture=$thisuser->picture;
            //$record['picture']=$picture['uri'];
            if(isset($picture->uri))$record['picture']= image_style_url('thumbnail', $picture->uri);
            if(isset($picture->uri))$record['picture-home']= image_style_url('home-idea', $picture->uri);
            else $record['picture']='';
            // echo "<br>";
            $userlist=$recordu;
        }

        $userlist['about'] = json_decode($userlist['about']);
        $userlist['location'] = json_decode($userlist['location']);
        $userlist['skills'] = json_decode($userlist['skills']);
        $userlist['education'] = json_decode($userlist['education']);

        $record['user']=$userlist;
            $records[]=$record;




    }

    echo json_encode(@$records);

}