<?php
/**
 * Created by PhpStorm.
 * User: debasis
 * Date: 16/6/15
 * Time: 12:04 AM
 */
$crossoriginallowed="http://voortal.hagencompaniesonline.com";

header('Content-type: text/html');
header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');


function todo_notes_init() // init function called by defaulted when this module loaded by system
{

    //echo $GLOBALS['theme'];
    //echo 5656;
    //echo user_authenticate('debasis','Pp@ss1234');

//echo "kl";
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');



}

function todo_notes_menu()
{
    $items = array();

    $items['addnotes'] = array(
        'title' => 'login',
        'page callback' => 'addnotes',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['noteslist'] = array(
        'title' => 'login',
        'page callback' => 'noteslist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );

    return $items;
}


function noteslist(){
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $query = db_select('todoandnotes', 'notes');
    //$query->join('user_table', 'ut', 'u.uid = ut.userid');
    $query->fields('notes', array('id','user_id','note','type','timecreated'));
    //$query->fields('ut',array('fname','lname'));
    // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
    //->condition('de.domain_id', 25, '=')
    //->range(0, 20);
    $result = $query->execute();

    while($record = $result->fetchAssoc()) {
        //print_r($record);
        //$record['id']=time_elapsed_string($record['created']);
        //$record['id']=($record['created']);
        //// echo "<br>";
        $record['user_id'];



        $queryu = db_select('users', 'u');
        $queryu->join('user_table', 'ut', 'u.uid = ut.userid');
        $queryu->fields('u', array('uid','name','mail','status','created'),'ut',array('fname','lname'));
        $queryu->fields('ut',array('fname','lname','about','location','education','skills'))
            // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
            ->condition('u.uid', $record['user_id'], '=');
            //->condition('u.uid', 74, '=');
        //->range(0, 20);
        $resultu = $queryu->execute();

        while($recordu = $resultu->fetchAssoc()) {
            //print_r($record);
            //$record['roles']=
            //// echo "<br>";
            $thisuser = user_load($recordu['uid']);
            // var_dump($thisuser);
            //$record['roles']=$thisuser->roles;
            foreach($thisuser->roles as $index=>$val){
                if($index!=2) $recordu['roles']=$index;
            }
            $picture=$thisuser->picture;
            //$record['picture']=$picture['uri'];
            if(isset($picture->uri))$record['picture']= image_style_url('thumbnail', $picture->uri);
            //if(isset($picture->uri))$record['picture-home']= image_style_url('home-idea', $picture->uri);
            else $record['picture']='';
            // echo "<br>";
            $userlist=$recordu;
        }

        $userlist['about'] = json_decode($userlist['about']);
        $userlist['location'] = json_decode($userlist['location']);
        $userlist['skills'] = json_decode($userlist['skills']);
        $userlist['education'] = json_decode($userlist['education']);

        $record['user']=$userlist;


        $records[]=$record;

    }

    echo json_encode(@$records);

}



function addnotes(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: http://voortal.hagencompaniesonline.com');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');



    //$_POST['fname']='iu';

    $data['id'] = db_insert('todoandnotes')->fields(array('user_id','type','note','timecreated'))
        ->values(array(@$_POST['user_id'],@$_POST['type'],@$_POST['note'],time()))->execute();

    /*$id = db_insert('ideas')
        ->fields(array(
            'intvar' => 5,
            'stringvar' => 'hello world',
            'floatvar' => 3.14,
        ))
        ->execute();*/


    //print_r($_POST);
    //echo "roles :<br>";
    //print_r($roles);
    $data['status'] = 'success';
    //$data['id'] = db_last_insert_id('ideas', 'id');

    //$data['msg'] = 'Email already exists..';
    //echo json_encode($data);
    return;

}